//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notification.API.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyScheduleDetail
    {
        public int Id { get; set; }
        public string Market { get; set; }
        public string Type { get; set; }
        public System.DateTime CreatedDttm { get; set; }
        public System.DateTime ModifiedDttm { get; set; }
        public string Frequency { get; set; }
    }
}
